# Donacije i Community
Na linku ispod možete pristupiti stranici za donacije te također uključiti se u *community* te pomoći oko daljnjeg razvoja aplikacije.

patreon: [akara211](https://patreon.com/user?u=86650949&utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link)

[Lets go to Quora](https://www.quora.com)
